---
# -*- coding: utf-8 -*-

image: koalaman/shellcheck-alpine:stable

before_script:
  - shellcheck --version
  - pwd
  - ls -lht

stages:
  - shellcheck

shellcheck:
  stage: shellcheck
  script:
    - ./gl-src-check
