#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null
# shellcheck disable=SC2086

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Run Pipeline

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Example

\`\`\`bash

  $BIN

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

CURRENT_BRANCH="$(git branch | grep -E '^\*' | awk '{print $2}')"

[[ -n "$YAML"      ]] || YAML='.gitlab-ci.yml'
[[ -e "$YAML"      ]] || die "NOT FOUND $YAML"
[[ -n "$BRANCH"    ]] || BRANCH="$CURRENT_BRANCH"
[[ -n "$VARIABLES" ]] && VARIABLES="--variables $VARIABLES"

gl ci run -b "$BRANCH" $VARIABLES
