#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Get the issue title with _URL_ link in _Markdown_ as a list item

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Example

\`\`\`bash

  $BIN 1

  - publish first public version [gitlab-bash-utils#1](https://gitlab.com/gcoop-libre/gitlab-bash-utils/-/issues/1)

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -e "$GIT_CFG" ]] || die "NOT FOUND $GIT_CFG"
[[ -z "$1"       ]] && die "EMPTY ISSUE"

ISSUE="$1"
REGEX='^[0-9]+$'

[[ "$ISSUE" =~ $REGEX ]] || exit 1

LINK="$(gl-issue-link "$ISSUE")"

printf "%s %s\n" '-' "$LINK"
