#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Get filtered issue list

### Usage

\`\`\`bash

  $BIN

\`\`\`

### Example

\`\`\`bash

  $BIN 1


\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -n "$GL_DEFAULT_ASSIGNEE" ]] && ASSIGNEE="$GL_DEFAULT_ASSIGNEE"
[[ -n "$GL_GROUP_DEFAULT"   ]] && V="GL_GROUP_${GL_GROUP_DEFAULT^^}_DIR"
GL_GROUP_DIR_BASE="${!V}"
GL_GROUP_PROJECTS="GL_GROUP_${GL_GROUP_DEFAULT^^}_PROJECTS_${ASSIGNEE^^}"
PROJECTS="${!GL_GROUP_PROJECTS}"

[[ -z "$PROJECTS" ]] && die "UNDEFINED $GL_GROUP_PROJECTS"

echo "$PROJECTS" | tr ' ' '\n' | while read -r PROJECT
do

	cd "$GL_GROUP_DIR_BASE/$PROJECT" || continue
  printf "\\n## %s\\n\\n" "$PROJECT"
  gl-issue-assignee

done

cd "$GL_GROUP_DIR_BASE" || exit 1
