#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Insert \`/spend\` time in _Issue_ converting from \`hh:mm\` time format

### Usage

\`\`\`bash

  $BIN ISSUE_ID

\`\`\`

### Example

\`\`\`bash

  $BIN 14 00:01
  send /spend 01m to 14

  git log -1 | $BIN 14
  send /spend 01m to 14

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

if [[ -e "$TMPI" ]]
then
  ISSUE_ID="$(head -1 "$TMPI" | grep -Eo '#[0-9]+' | tr -d '#')"
  TIME="$(tail  -1 "$TMPI" | grep -Eo '[0-9]{2}:[0-9]{2}')"
  [[ -z "$ISSUE_ID" ]] && ISSUE_ID="$1"
else
  ISSUE_ID="$1"
  TIME="$2"
fi

ISSUE_REGEX='[0-9]+'
[[ -z "$ISSUE_ID" ]] && die "EMPTY ISSUE_ID"
[[ "$ISSUE_ID" =~ $ISSUE_REGEX ]] || die "INVALID ISSUE_ID: $ISSUE_ID"

SPEND_REGEX='[0-9]{2}:[0-9]{2}'
[[ -z "$TIME"     ]] && die "EMPTY TIME"
SPEND="$(echo "$TIME" | time2spend)"

[[ "$TIME" =~ $SPEND_REGEX ]] || die "INVALID TIME FORMAT: $SPEND"

printf "send %s to %s\\n" "$SPEND" "$ISSUE_ID"
gl issue note "$ISSUE_ID" --message "$SPEND"
