#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck disable=SC2016

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Create issue with defaults defined in \`~/.gl-config\`

### Usage

\`\`\`bash

  $BIN TITLE [DESCRIPTION]

\`\`\`

### Example

\`\`\`bash

  $BIN 'publish first public version' 'commit actual state of scripts art'

    - Creating issue in gcoop-libre/gitlab-bash-utils
    #1 publish first public version (less than a minute ago)
     https://gitlab.com/gcoop-libre/gitlab-bash-utils/-/issues/1

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

fi

if [[ -e "$TMPI" ]]
then
  TITLE="$(head -1 "$TMPI")"
  DESCRIPTION="$(tail -n+2 "$TMPI" | sed 's/`/\\`/g')"
else
  TITLE="$1"
  DESCRIPTION="$2"
fi

[[ -z "$TITLE"         ]] && die "empty TITLE"
[[ -z "$DESCRIPTION"   ]] && DESCRIPTION="$TITLE"
[[ -n "$ASSIGNEE"      ]] || ASSIGNEE="$GL_DEFAULT_ASSIGNEE"
[[ -z "$ASSIGNEE"      ]] && die "EMPTY ASSIGNEE"
[[ -n "$LABELS"        ]] || LABELS='wip'

gl issue new                   \
  --title "$TITLE"             \
  --assignee "$ASSIGNEE"       \
  --label "$LABELS"            \
  --description "$DESCRIPTION"
