#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null
# shellcheck disable=SC2086

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Get title of Issue

### Usage

\`\`\`bash

  $BIN ISSUE_ID

\`\`\`

### Example

\`\`\`bash

  $BIN 1

  publish first public version

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -e "$GIT_CFG" ]] || die "INVALID GIT REPOSITORY"
[[ -n "$ISSUE"   ]] || ISSUE="$VALIDATE_ISSUE"
[[ -z "$ISSUE"   ]] && ISSUE="$1"
[[ -z "$ISSUE"   ]] && die "EMPTY ISSUE ID"

validate_issue "$ISSUE"

gl issue view "$ISSUE_ID" $REPO \
  | tee                         \
  | grep title:                 \
  | cut -d: -f2-                \
  | tr -d '\t'
