#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` assing _MR_ to default assignee or specified assignee

### Usage

\`\`\`bash

  $BIN ASSINEE MR

\`\`\`

### Example

\`\`\`bash

  $BIN osiux 6

  - Updating merge request !6
  ✓ assigned to "@osiux"
  !6 Draft: Resolve release/0.1.0 'include uncommited scripts and generate first public version 0.1.0' (release/0.1.0)
   https://gitlab.com/osiux/org-bash-utils/-/merge_requests/6

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -e "$GIT_CFG"  ]] || die "NOT FOUND $GIT_CFG"

[[ -z "$1"        ]] || ASSIGNEE="$1"
[[ -z "$ASSIGNEE" ]] && die "EMPTY ASSIGNEE"
[[ -z "$2"        ]] || MR="$2"
[[ -z "$MR"       ]] && die "EMPTY MR"

gl mr update --assignee "$ASSIGNEE" "$MR"
