#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/gl-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Create a project

### Usage

\`\`\`bash

  $BIN PROJECT_NAME GROUP_ID

\`\`\`

### Example

\`\`\`bash

  $BIN test 11

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

[[ -e "$GIT_CFG"      ]] || die "NOT FOUND $GIT_CFG"
[[ -z "$GLAB_TOKEN"   ]] && die "UNDEFINED GLAB_TOKEN TRY DEFINE IN $GIT_CFG"
[[ -z "$1"            ]] || PROJECT_NAME="$1"
[[ -n "$PROJECT_NAME" ]] || die "UNDEFINED PROJECT_NAME"
[[ -z "$PROJECT_NAME" ]] && die "EMPTY PROJECT_NAME"
[[ -z "$2"            ]] || GROUP_ID="$2"
[[ -n "$GROUP_ID"     ]] || die "UNDEFINED GROUP_ID"
[[ -z "$GROUP_ID"     ]] && die "EMPTY GROUP_ID"

project_new "$PROJECT_NAME" "$GROUP_ID"
