#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2002

TIME_REGEX='[0-9]{2}:[0-9]{2}'

TMPI="$(mktemp)"

if [[ ! -t 0 ]]
then

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

else

  [[ -z "$1"   ]] && exit 1
  echo "$1" > "$TMPI"

fi

[[ ! -e "$TMPI" ]] && exit 1

sed -i $'1s/^\uFEFF//' "$TMPI"

cat "$TMPI"        \
  | sed 's/@ //g'  \
  | sed 's/ hs//g' \
  | while read -r TIME
do

[[ "$TIME" =  '00:00'     ]] && continue
[[ "$TIME" =~ $TIME_REGEX ]] || continue

HH="$(echo "$TIME" | cut -d: -f1)"
MM="$(echo "$TIME" | cut -d: -f2)"
SPEND="$(echo "${HH}h${MM}m" | sed 's/00h//g' | sed 's/00m//g')"

[[ -z "$SPEND" ]] || echo "/spend $SPEND"

done
