#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if [[ ! -t 0 ]]
then
  TMPI="$(mktemp)"

  true > "$TMPI"

  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done

  URL="$(cat "$TMPI")"
fi

[[ -z "$1"   ]] || URL="$1"
[[ -z "$URL" ]] && exit 1

URL="${URL%\?*}"
ID="$(echo "$URL" | rev | cut -d '/' -f1 | rev)"

PREFIX=''
if [[ "$URL" =~ "/issues/" ]]
then
  PREFIX="$(echo "$URL" | rev | cut -d '/' -f4 | rev)#"
fi

if [[ "$URL" =~ "/merge_requests/" ]]
then
  PREFIX="$(echo "$URL" | rev | cut -d '/' -f4 | rev)!"
fi

printf "[%s](%s)" "${PREFIX}${ID}" "$URL"
